version: '3'
services:
  tcp:
    build:
      dockerfile: ../../Dockerfile
      context: ./proxies/tcp
    command: --addr=0.0.0.0:8080
  http:
    build:
      dockerfile: ../../Dockerfile
      context: ./proxies/http
    command: --addr=0.0.0.0:8080
  reverse:
    build:
      dockerfile: ../../Dockerfile
      context: ./proxies/reverse
    command: --addr=0.0.0.0:8080
  gateway:
    build:
      dockerfile: ../Dockerfile
      context: ./gateway
    # If you don't specify the schema on the proxy and mirrors params it will fail but not panic due to parsing ambiguity in the `url.Parse` stdlib function 
    command: --addr=0.0.0.0:8080 --proxy=http://tcp:8080 --mirrors=http://http:8080,http://reverse:8080
    ports:
      - "8080:8080"
