## Dynamic configuration
http:
  routers:
    reverse-proxy:
      rule: "Path(`/`)"
      service: proxy

  services:
    proxy:
      mirroring:
        service: tcp
        # maxBodySize is the maximum size allowed for the body of the request.
        # If the body is larger, the request is not mirrored.
        # Default value is -1, which means unlimited size.
        # maxBodySize: 1024
        mirrors:
        - name: http
          percent: 100
        - name: reverse
          percent: 100

    tcp:
      loadBalancer:
        servers:
        - url: "http://tcp:8080/"

    http:
      loadBalancer:
        servers:
        - url: "http://http:8080/"

    reverse:
      loadBalancer:
        servers:
        - url: "http://reverse:8080/"