## Dynamic configuration
http:
  routers:
    reverse-proxy:
      rule: "Path(`/`)"
      service: proxy

  services:
    proxy:
      loadBalancer:
        servers:
        - url: "http://gateway:8080/"

    tcp:
      loadBalancer:
        servers:
        - url: "http://tcp:8080/"

    http:
      loadBalancer:
        servers:
        - url: "http://http:8080/"

    reverse:
      loadBalancer:
        servers:
        - url: "http://reverse:8080/"